/*
CNS-BACKEND

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cnsbackend

import (
	"encoding/json"
)

// ServicesMakeRegisterOrderResp struct for ServicesMakeRegisterOrderResp
type ServicesMakeRegisterOrderResp struct {
	CodeUrl *string `json:"code_url,omitempty"`
	CommitHash *string `json:"commit_hash,omitempty"`
	H5Url *string `json:"h5_url,omitempty"`
	TradeNo *string `json:"trade_no,omitempty"`
	TradeProvider *string `json:"trade_provider,omitempty"`
	TradeType *string `json:"trade_type,omitempty"`
	WapUrl *string `json:"wap_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServicesMakeRegisterOrderResp ServicesMakeRegisterOrderResp

// NewServicesMakeRegisterOrderResp instantiates a new ServicesMakeRegisterOrderResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesMakeRegisterOrderResp() *ServicesMakeRegisterOrderResp {
	this := ServicesMakeRegisterOrderResp{}
	return &this
}

// NewServicesMakeRegisterOrderRespWithDefaults instantiates a new ServicesMakeRegisterOrderResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesMakeRegisterOrderRespWithDefaults() *ServicesMakeRegisterOrderResp {
	this := ServicesMakeRegisterOrderResp{}
	return &this
}

// GetCodeUrl returns the CodeUrl field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetCodeUrl() string {
	if o == nil || isNil(o.CodeUrl) {
		var ret string
		return ret
	}
	return *o.CodeUrl
}

// GetCodeUrlOk returns a tuple with the CodeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetCodeUrlOk() (*string, bool) {
	if o == nil || isNil(o.CodeUrl) {
    return nil, false
	}
	return o.CodeUrl, true
}

// HasCodeUrl returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasCodeUrl() bool {
	if o != nil && !isNil(o.CodeUrl) {
		return true
	}

	return false
}

// SetCodeUrl gets a reference to the given string and assigns it to the CodeUrl field.
func (o *ServicesMakeRegisterOrderResp) SetCodeUrl(v string) {
	o.CodeUrl = &v
}

// GetCommitHash returns the CommitHash field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetCommitHash() string {
	if o == nil || isNil(o.CommitHash) {
		var ret string
		return ret
	}
	return *o.CommitHash
}

// GetCommitHashOk returns a tuple with the CommitHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetCommitHashOk() (*string, bool) {
	if o == nil || isNil(o.CommitHash) {
    return nil, false
	}
	return o.CommitHash, true
}

// HasCommitHash returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasCommitHash() bool {
	if o != nil && !isNil(o.CommitHash) {
		return true
	}

	return false
}

// SetCommitHash gets a reference to the given string and assigns it to the CommitHash field.
func (o *ServicesMakeRegisterOrderResp) SetCommitHash(v string) {
	o.CommitHash = &v
}

// GetH5Url returns the H5Url field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetH5Url() string {
	if o == nil || isNil(o.H5Url) {
		var ret string
		return ret
	}
	return *o.H5Url
}

// GetH5UrlOk returns a tuple with the H5Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetH5UrlOk() (*string, bool) {
	if o == nil || isNil(o.H5Url) {
    return nil, false
	}
	return o.H5Url, true
}

// HasH5Url returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasH5Url() bool {
	if o != nil && !isNil(o.H5Url) {
		return true
	}

	return false
}

// SetH5Url gets a reference to the given string and assigns it to the H5Url field.
func (o *ServicesMakeRegisterOrderResp) SetH5Url(v string) {
	o.H5Url = &v
}

// GetTradeNo returns the TradeNo field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetTradeNo() string {
	if o == nil || isNil(o.TradeNo) {
		var ret string
		return ret
	}
	return *o.TradeNo
}

// GetTradeNoOk returns a tuple with the TradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetTradeNoOk() (*string, bool) {
	if o == nil || isNil(o.TradeNo) {
    return nil, false
	}
	return o.TradeNo, true
}

// HasTradeNo returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasTradeNo() bool {
	if o != nil && !isNil(o.TradeNo) {
		return true
	}

	return false
}

// SetTradeNo gets a reference to the given string and assigns it to the TradeNo field.
func (o *ServicesMakeRegisterOrderResp) SetTradeNo(v string) {
	o.TradeNo = &v
}

// GetTradeProvider returns the TradeProvider field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetTradeProvider() string {
	if o == nil || isNil(o.TradeProvider) {
		var ret string
		return ret
	}
	return *o.TradeProvider
}

// GetTradeProviderOk returns a tuple with the TradeProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetTradeProviderOk() (*string, bool) {
	if o == nil || isNil(o.TradeProvider) {
    return nil, false
	}
	return o.TradeProvider, true
}

// HasTradeProvider returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasTradeProvider() bool {
	if o != nil && !isNil(o.TradeProvider) {
		return true
	}

	return false
}

// SetTradeProvider gets a reference to the given string and assigns it to the TradeProvider field.
func (o *ServicesMakeRegisterOrderResp) SetTradeProvider(v string) {
	o.TradeProvider = &v
}

// GetTradeType returns the TradeType field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetTradeType() string {
	if o == nil || isNil(o.TradeType) {
		var ret string
		return ret
	}
	return *o.TradeType
}

// GetTradeTypeOk returns a tuple with the TradeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetTradeTypeOk() (*string, bool) {
	if o == nil || isNil(o.TradeType) {
    return nil, false
	}
	return o.TradeType, true
}

// HasTradeType returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasTradeType() bool {
	if o != nil && !isNil(o.TradeType) {
		return true
	}

	return false
}

// SetTradeType gets a reference to the given string and assigns it to the TradeType field.
func (o *ServicesMakeRegisterOrderResp) SetTradeType(v string) {
	o.TradeType = &v
}

// GetWapUrl returns the WapUrl field value if set, zero value otherwise.
func (o *ServicesMakeRegisterOrderResp) GetWapUrl() string {
	if o == nil || isNil(o.WapUrl) {
		var ret string
		return ret
	}
	return *o.WapUrl
}

// GetWapUrlOk returns a tuple with the WapUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRegisterOrderResp) GetWapUrlOk() (*string, bool) {
	if o == nil || isNil(o.WapUrl) {
    return nil, false
	}
	return o.WapUrl, true
}

// HasWapUrl returns a boolean if a field has been set.
func (o *ServicesMakeRegisterOrderResp) HasWapUrl() bool {
	if o != nil && !isNil(o.WapUrl) {
		return true
	}

	return false
}

// SetWapUrl gets a reference to the given string and assigns it to the WapUrl field.
func (o *ServicesMakeRegisterOrderResp) SetWapUrl(v string) {
	o.WapUrl = &v
}

func (o ServicesMakeRegisterOrderResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CodeUrl) {
		toSerialize["code_url"] = o.CodeUrl
	}
	if !isNil(o.CommitHash) {
		toSerialize["commit_hash"] = o.CommitHash
	}
	if !isNil(o.H5Url) {
		toSerialize["h5_url"] = o.H5Url
	}
	if !isNil(o.TradeNo) {
		toSerialize["trade_no"] = o.TradeNo
	}
	if !isNil(o.TradeProvider) {
		toSerialize["trade_provider"] = o.TradeProvider
	}
	if !isNil(o.TradeType) {
		toSerialize["trade_type"] = o.TradeType
	}
	if !isNil(o.WapUrl) {
		toSerialize["wap_url"] = o.WapUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServicesMakeRegisterOrderResp) UnmarshalJSON(bytes []byte) (err error) {
	varServicesMakeRegisterOrderResp := _ServicesMakeRegisterOrderResp{}

	if err = json.Unmarshal(bytes, &varServicesMakeRegisterOrderResp); err == nil {
		*o = ServicesMakeRegisterOrderResp(varServicesMakeRegisterOrderResp)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "code_url")
		delete(additionalProperties, "commit_hash")
		delete(additionalProperties, "h5_url")
		delete(additionalProperties, "trade_no")
		delete(additionalProperties, "trade_provider")
		delete(additionalProperties, "trade_type")
		delete(additionalProperties, "wap_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesMakeRegisterOrderResp struct {
	value *ServicesMakeRegisterOrderResp
	isSet bool
}

func (v NullableServicesMakeRegisterOrderResp) Get() *ServicesMakeRegisterOrderResp {
	return v.value
}

func (v *NullableServicesMakeRegisterOrderResp) Set(val *ServicesMakeRegisterOrderResp) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesMakeRegisterOrderResp) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesMakeRegisterOrderResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesMakeRegisterOrderResp(val *ServicesMakeRegisterOrderResp) *NullableServicesMakeRegisterOrderResp {
	return &NullableServicesMakeRegisterOrderResp{value: val, isSet: true}
}

func (v NullableServicesMakeRegisterOrderResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesMakeRegisterOrderResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


