/*
CNS-BACKEND

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cnsbackend

import (
	"encoding/json"
)

// ModelsRegisterCore struct for ModelsRegisterCore
type ModelsRegisterCore struct {
	// 单位为分
	Amount *int32 `json:"amount,omitempty"`
	AppName *string `json:"app_name,omitempty"`
	CodeUrl *string `json:"code_url,omitempty"`
	CommitHash *string `json:"commit_hash,omitempty"`
	Description *string `json:"description,omitempty"`
	H5Url *string `json:"h5_url,omitempty"`
	// 二维码宽度。 只有alipay，且 trade type 为 h5 模式有效，qr pay mode 为4 时有效； 用法参考 https://opendocs.alipay.com/apis/api_1/alipay.trade.page.pay?scene=22
	QrCodeWidth *string `json:"qr_code_width,omitempty"`
	// 支付二维码模式。 只有alipay，且 trade type 为 h5 模式有效; 用法参考 https://opendocs.alipay.com/apis/api_1/alipay.trade.page.pay?scene=22
	QrPayMode *string `json:"qr_pay_mode,omitempty"`
	RefundState *string `json:"refund_state,omitempty"`
	// 付款成功后的跳转链接。只有alipay，且 trade type 为 h5 模式有效; 用法参考 https://opendocs.alipay.com/apis/api_1/alipay.trade.page.pay?scene=22
	ReturnUrl *string `json:"return_url,omitempty"`
	TimeExpire *string `json:"time_expire,omitempty"`
	TradeNo *string `json:"trade_no,omitempty"`
	TradeProvider *string `json:"trade_provider,omitempty"`
	TradeState *string `json:"trade_state,omitempty"`
	TradeType *string `json:"trade_type,omitempty"`
	TxError *string `json:"tx_error,omitempty"`
	TxHash *string `json:"tx_hash,omitempty"`
	TxState *int32 `json:"tx_state,omitempty"`
	WapUrl *string `json:"wap_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsRegisterCore ModelsRegisterCore

// NewModelsRegisterCore instantiates a new ModelsRegisterCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsRegisterCore() *ModelsRegisterCore {
	this := ModelsRegisterCore{}
	return &this
}

// NewModelsRegisterCoreWithDefaults instantiates a new ModelsRegisterCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsRegisterCoreWithDefaults() *ModelsRegisterCore {
	this := ModelsRegisterCore{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetAmount() int32 {
	if o == nil || isNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetAmountOk() (*int32, bool) {
	if o == nil || isNil(o.Amount) {
    return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasAmount() bool {
	if o != nil && !isNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ModelsRegisterCore) SetAmount(v int32) {
	o.Amount = &v
}

// GetAppName returns the AppName field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetAppName() string {
	if o == nil || isNil(o.AppName) {
		var ret string
		return ret
	}
	return *o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetAppNameOk() (*string, bool) {
	if o == nil || isNil(o.AppName) {
    return nil, false
	}
	return o.AppName, true
}

// HasAppName returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasAppName() bool {
	if o != nil && !isNil(o.AppName) {
		return true
	}

	return false
}

// SetAppName gets a reference to the given string and assigns it to the AppName field.
func (o *ModelsRegisterCore) SetAppName(v string) {
	o.AppName = &v
}

// GetCodeUrl returns the CodeUrl field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetCodeUrl() string {
	if o == nil || isNil(o.CodeUrl) {
		var ret string
		return ret
	}
	return *o.CodeUrl
}

// GetCodeUrlOk returns a tuple with the CodeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetCodeUrlOk() (*string, bool) {
	if o == nil || isNil(o.CodeUrl) {
    return nil, false
	}
	return o.CodeUrl, true
}

// HasCodeUrl returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasCodeUrl() bool {
	if o != nil && !isNil(o.CodeUrl) {
		return true
	}

	return false
}

// SetCodeUrl gets a reference to the given string and assigns it to the CodeUrl field.
func (o *ModelsRegisterCore) SetCodeUrl(v string) {
	o.CodeUrl = &v
}

// GetCommitHash returns the CommitHash field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetCommitHash() string {
	if o == nil || isNil(o.CommitHash) {
		var ret string
		return ret
	}
	return *o.CommitHash
}

// GetCommitHashOk returns a tuple with the CommitHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetCommitHashOk() (*string, bool) {
	if o == nil || isNil(o.CommitHash) {
    return nil, false
	}
	return o.CommitHash, true
}

// HasCommitHash returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasCommitHash() bool {
	if o != nil && !isNil(o.CommitHash) {
		return true
	}

	return false
}

// SetCommitHash gets a reference to the given string and assigns it to the CommitHash field.
func (o *ModelsRegisterCore) SetCommitHash(v string) {
	o.CommitHash = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModelsRegisterCore) SetDescription(v string) {
	o.Description = &v
}

// GetH5Url returns the H5Url field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetH5Url() string {
	if o == nil || isNil(o.H5Url) {
		var ret string
		return ret
	}
	return *o.H5Url
}

// GetH5UrlOk returns a tuple with the H5Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetH5UrlOk() (*string, bool) {
	if o == nil || isNil(o.H5Url) {
    return nil, false
	}
	return o.H5Url, true
}

// HasH5Url returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasH5Url() bool {
	if o != nil && !isNil(o.H5Url) {
		return true
	}

	return false
}

// SetH5Url gets a reference to the given string and assigns it to the H5Url field.
func (o *ModelsRegisterCore) SetH5Url(v string) {
	o.H5Url = &v
}

// GetQrCodeWidth returns the QrCodeWidth field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetQrCodeWidth() string {
	if o == nil || isNil(o.QrCodeWidth) {
		var ret string
		return ret
	}
	return *o.QrCodeWidth
}

// GetQrCodeWidthOk returns a tuple with the QrCodeWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetQrCodeWidthOk() (*string, bool) {
	if o == nil || isNil(o.QrCodeWidth) {
    return nil, false
	}
	return o.QrCodeWidth, true
}

// HasQrCodeWidth returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasQrCodeWidth() bool {
	if o != nil && !isNil(o.QrCodeWidth) {
		return true
	}

	return false
}

// SetQrCodeWidth gets a reference to the given string and assigns it to the QrCodeWidth field.
func (o *ModelsRegisterCore) SetQrCodeWidth(v string) {
	o.QrCodeWidth = &v
}

// GetQrPayMode returns the QrPayMode field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetQrPayMode() string {
	if o == nil || isNil(o.QrPayMode) {
		var ret string
		return ret
	}
	return *o.QrPayMode
}

// GetQrPayModeOk returns a tuple with the QrPayMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetQrPayModeOk() (*string, bool) {
	if o == nil || isNil(o.QrPayMode) {
    return nil, false
	}
	return o.QrPayMode, true
}

// HasQrPayMode returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasQrPayMode() bool {
	if o != nil && !isNil(o.QrPayMode) {
		return true
	}

	return false
}

// SetQrPayMode gets a reference to the given string and assigns it to the QrPayMode field.
func (o *ModelsRegisterCore) SetQrPayMode(v string) {
	o.QrPayMode = &v
}

// GetRefundState returns the RefundState field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetRefundState() string {
	if o == nil || isNil(o.RefundState) {
		var ret string
		return ret
	}
	return *o.RefundState
}

// GetRefundStateOk returns a tuple with the RefundState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetRefundStateOk() (*string, bool) {
	if o == nil || isNil(o.RefundState) {
    return nil, false
	}
	return o.RefundState, true
}

// HasRefundState returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasRefundState() bool {
	if o != nil && !isNil(o.RefundState) {
		return true
	}

	return false
}

// SetRefundState gets a reference to the given string and assigns it to the RefundState field.
func (o *ModelsRegisterCore) SetRefundState(v string) {
	o.RefundState = &v
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetReturnUrl() string {
	if o == nil || isNil(o.ReturnUrl) {
		var ret string
		return ret
	}
	return *o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetReturnUrlOk() (*string, bool) {
	if o == nil || isNil(o.ReturnUrl) {
    return nil, false
	}
	return o.ReturnUrl, true
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasReturnUrl() bool {
	if o != nil && !isNil(o.ReturnUrl) {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given string and assigns it to the ReturnUrl field.
func (o *ModelsRegisterCore) SetReturnUrl(v string) {
	o.ReturnUrl = &v
}

// GetTimeExpire returns the TimeExpire field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTimeExpire() string {
	if o == nil || isNil(o.TimeExpire) {
		var ret string
		return ret
	}
	return *o.TimeExpire
}

// GetTimeExpireOk returns a tuple with the TimeExpire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTimeExpireOk() (*string, bool) {
	if o == nil || isNil(o.TimeExpire) {
    return nil, false
	}
	return o.TimeExpire, true
}

// HasTimeExpire returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTimeExpire() bool {
	if o != nil && !isNil(o.TimeExpire) {
		return true
	}

	return false
}

// SetTimeExpire gets a reference to the given string and assigns it to the TimeExpire field.
func (o *ModelsRegisterCore) SetTimeExpire(v string) {
	o.TimeExpire = &v
}

// GetTradeNo returns the TradeNo field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTradeNo() string {
	if o == nil || isNil(o.TradeNo) {
		var ret string
		return ret
	}
	return *o.TradeNo
}

// GetTradeNoOk returns a tuple with the TradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTradeNoOk() (*string, bool) {
	if o == nil || isNil(o.TradeNo) {
    return nil, false
	}
	return o.TradeNo, true
}

// HasTradeNo returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTradeNo() bool {
	if o != nil && !isNil(o.TradeNo) {
		return true
	}

	return false
}

// SetTradeNo gets a reference to the given string and assigns it to the TradeNo field.
func (o *ModelsRegisterCore) SetTradeNo(v string) {
	o.TradeNo = &v
}

// GetTradeProvider returns the TradeProvider field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTradeProvider() string {
	if o == nil || isNil(o.TradeProvider) {
		var ret string
		return ret
	}
	return *o.TradeProvider
}

// GetTradeProviderOk returns a tuple with the TradeProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTradeProviderOk() (*string, bool) {
	if o == nil || isNil(o.TradeProvider) {
    return nil, false
	}
	return o.TradeProvider, true
}

// HasTradeProvider returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTradeProvider() bool {
	if o != nil && !isNil(o.TradeProvider) {
		return true
	}

	return false
}

// SetTradeProvider gets a reference to the given string and assigns it to the TradeProvider field.
func (o *ModelsRegisterCore) SetTradeProvider(v string) {
	o.TradeProvider = &v
}

// GetTradeState returns the TradeState field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTradeState() string {
	if o == nil || isNil(o.TradeState) {
		var ret string
		return ret
	}
	return *o.TradeState
}

// GetTradeStateOk returns a tuple with the TradeState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTradeStateOk() (*string, bool) {
	if o == nil || isNil(o.TradeState) {
    return nil, false
	}
	return o.TradeState, true
}

// HasTradeState returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTradeState() bool {
	if o != nil && !isNil(o.TradeState) {
		return true
	}

	return false
}

// SetTradeState gets a reference to the given string and assigns it to the TradeState field.
func (o *ModelsRegisterCore) SetTradeState(v string) {
	o.TradeState = &v
}

// GetTradeType returns the TradeType field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTradeType() string {
	if o == nil || isNil(o.TradeType) {
		var ret string
		return ret
	}
	return *o.TradeType
}

// GetTradeTypeOk returns a tuple with the TradeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTradeTypeOk() (*string, bool) {
	if o == nil || isNil(o.TradeType) {
    return nil, false
	}
	return o.TradeType, true
}

// HasTradeType returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTradeType() bool {
	if o != nil && !isNil(o.TradeType) {
		return true
	}

	return false
}

// SetTradeType gets a reference to the given string and assigns it to the TradeType field.
func (o *ModelsRegisterCore) SetTradeType(v string) {
	o.TradeType = &v
}

// GetTxError returns the TxError field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTxError() string {
	if o == nil || isNil(o.TxError) {
		var ret string
		return ret
	}
	return *o.TxError
}

// GetTxErrorOk returns a tuple with the TxError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTxErrorOk() (*string, bool) {
	if o == nil || isNil(o.TxError) {
    return nil, false
	}
	return o.TxError, true
}

// HasTxError returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTxError() bool {
	if o != nil && !isNil(o.TxError) {
		return true
	}

	return false
}

// SetTxError gets a reference to the given string and assigns it to the TxError field.
func (o *ModelsRegisterCore) SetTxError(v string) {
	o.TxError = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTxHash() string {
	if o == nil || isNil(o.TxHash) {
		var ret string
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTxHashOk() (*string, bool) {
	if o == nil || isNil(o.TxHash) {
    return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTxHash() bool {
	if o != nil && !isNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given string and assigns it to the TxHash field.
func (o *ModelsRegisterCore) SetTxHash(v string) {
	o.TxHash = &v
}

// GetTxState returns the TxState field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetTxState() int32 {
	if o == nil || isNil(o.TxState) {
		var ret int32
		return ret
	}
	return *o.TxState
}

// GetTxStateOk returns a tuple with the TxState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetTxStateOk() (*int32, bool) {
	if o == nil || isNil(o.TxState) {
    return nil, false
	}
	return o.TxState, true
}

// HasTxState returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasTxState() bool {
	if o != nil && !isNil(o.TxState) {
		return true
	}

	return false
}

// SetTxState gets a reference to the given int32 and assigns it to the TxState field.
func (o *ModelsRegisterCore) SetTxState(v int32) {
	o.TxState = &v
}

// GetWapUrl returns the WapUrl field value if set, zero value otherwise.
func (o *ModelsRegisterCore) GetWapUrl() string {
	if o == nil || isNil(o.WapUrl) {
		var ret string
		return ret
	}
	return *o.WapUrl
}

// GetWapUrlOk returns a tuple with the WapUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRegisterCore) GetWapUrlOk() (*string, bool) {
	if o == nil || isNil(o.WapUrl) {
    return nil, false
	}
	return o.WapUrl, true
}

// HasWapUrl returns a boolean if a field has been set.
func (o *ModelsRegisterCore) HasWapUrl() bool {
	if o != nil && !isNil(o.WapUrl) {
		return true
	}

	return false
}

// SetWapUrl gets a reference to the given string and assigns it to the WapUrl field.
func (o *ModelsRegisterCore) SetWapUrl(v string) {
	o.WapUrl = &v
}

func (o ModelsRegisterCore) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !isNil(o.AppName) {
		toSerialize["app_name"] = o.AppName
	}
	if !isNil(o.CodeUrl) {
		toSerialize["code_url"] = o.CodeUrl
	}
	if !isNil(o.CommitHash) {
		toSerialize["commit_hash"] = o.CommitHash
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.H5Url) {
		toSerialize["h5_url"] = o.H5Url
	}
	if !isNil(o.QrCodeWidth) {
		toSerialize["qr_code_width"] = o.QrCodeWidth
	}
	if !isNil(o.QrPayMode) {
		toSerialize["qr_pay_mode"] = o.QrPayMode
	}
	if !isNil(o.RefundState) {
		toSerialize["refund_state"] = o.RefundState
	}
	if !isNil(o.ReturnUrl) {
		toSerialize["return_url"] = o.ReturnUrl
	}
	if !isNil(o.TimeExpire) {
		toSerialize["time_expire"] = o.TimeExpire
	}
	if !isNil(o.TradeNo) {
		toSerialize["trade_no"] = o.TradeNo
	}
	if !isNil(o.TradeProvider) {
		toSerialize["trade_provider"] = o.TradeProvider
	}
	if !isNil(o.TradeState) {
		toSerialize["trade_state"] = o.TradeState
	}
	if !isNil(o.TradeType) {
		toSerialize["trade_type"] = o.TradeType
	}
	if !isNil(o.TxError) {
		toSerialize["tx_error"] = o.TxError
	}
	if !isNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	if !isNil(o.TxState) {
		toSerialize["tx_state"] = o.TxState
	}
	if !isNil(o.WapUrl) {
		toSerialize["wap_url"] = o.WapUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ModelsRegisterCore) UnmarshalJSON(bytes []byte) (err error) {
	varModelsRegisterCore := _ModelsRegisterCore{}

	if err = json.Unmarshal(bytes, &varModelsRegisterCore); err == nil {
		*o = ModelsRegisterCore(varModelsRegisterCore)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "app_name")
		delete(additionalProperties, "code_url")
		delete(additionalProperties, "commit_hash")
		delete(additionalProperties, "description")
		delete(additionalProperties, "h5_url")
		delete(additionalProperties, "qr_code_width")
		delete(additionalProperties, "qr_pay_mode")
		delete(additionalProperties, "refund_state")
		delete(additionalProperties, "return_url")
		delete(additionalProperties, "time_expire")
		delete(additionalProperties, "trade_no")
		delete(additionalProperties, "trade_provider")
		delete(additionalProperties, "trade_state")
		delete(additionalProperties, "trade_type")
		delete(additionalProperties, "tx_error")
		delete(additionalProperties, "tx_hash")
		delete(additionalProperties, "tx_state")
		delete(additionalProperties, "wap_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsRegisterCore struct {
	value *ModelsRegisterCore
	isSet bool
}

func (v NullableModelsRegisterCore) Get() *ModelsRegisterCore {
	return v.value
}

func (v *NullableModelsRegisterCore) Set(val *ModelsRegisterCore) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsRegisterCore) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsRegisterCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsRegisterCore(val *ModelsRegisterCore) *NullableModelsRegisterCore {
	return &NullableModelsRegisterCore{value: val, isSet: true}
}

func (v NullableModelsRegisterCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsRegisterCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


