/*
CNS-BACKEND

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cnsbackend

import (
	"encoding/json"
)

// ServicesMakeRenewOrderResp struct for ServicesMakeRenewOrderResp
type ServicesMakeRenewOrderResp struct {
	CodeUrl *string `json:"code_url,omitempty"`
	H5Url *string `json:"h5_url,omitempty"`
	Id *int32 `json:"id,omitempty"`
	TradeNo *string `json:"trade_no,omitempty"`
	TradeProvider *string `json:"trade_provider,omitempty"`
	TradeType *string `json:"trade_type,omitempty"`
	WapUrl *string `json:"wap_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServicesMakeRenewOrderResp ServicesMakeRenewOrderResp

// NewServicesMakeRenewOrderResp instantiates a new ServicesMakeRenewOrderResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesMakeRenewOrderResp() *ServicesMakeRenewOrderResp {
	this := ServicesMakeRenewOrderResp{}
	return &this
}

// NewServicesMakeRenewOrderRespWithDefaults instantiates a new ServicesMakeRenewOrderResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesMakeRenewOrderRespWithDefaults() *ServicesMakeRenewOrderResp {
	this := ServicesMakeRenewOrderResp{}
	return &this
}

// GetCodeUrl returns the CodeUrl field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetCodeUrl() string {
	if o == nil || isNil(o.CodeUrl) {
		var ret string
		return ret
	}
	return *o.CodeUrl
}

// GetCodeUrlOk returns a tuple with the CodeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetCodeUrlOk() (*string, bool) {
	if o == nil || isNil(o.CodeUrl) {
    return nil, false
	}
	return o.CodeUrl, true
}

// HasCodeUrl returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasCodeUrl() bool {
	if o != nil && !isNil(o.CodeUrl) {
		return true
	}

	return false
}

// SetCodeUrl gets a reference to the given string and assigns it to the CodeUrl field.
func (o *ServicesMakeRenewOrderResp) SetCodeUrl(v string) {
	o.CodeUrl = &v
}

// GetH5Url returns the H5Url field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetH5Url() string {
	if o == nil || isNil(o.H5Url) {
		var ret string
		return ret
	}
	return *o.H5Url
}

// GetH5UrlOk returns a tuple with the H5Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetH5UrlOk() (*string, bool) {
	if o == nil || isNil(o.H5Url) {
    return nil, false
	}
	return o.H5Url, true
}

// HasH5Url returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasH5Url() bool {
	if o != nil && !isNil(o.H5Url) {
		return true
	}

	return false
}

// SetH5Url gets a reference to the given string and assigns it to the H5Url field.
func (o *ServicesMakeRenewOrderResp) SetH5Url(v string) {
	o.H5Url = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ServicesMakeRenewOrderResp) SetId(v int32) {
	o.Id = &v
}

// GetTradeNo returns the TradeNo field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetTradeNo() string {
	if o == nil || isNil(o.TradeNo) {
		var ret string
		return ret
	}
	return *o.TradeNo
}

// GetTradeNoOk returns a tuple with the TradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetTradeNoOk() (*string, bool) {
	if o == nil || isNil(o.TradeNo) {
    return nil, false
	}
	return o.TradeNo, true
}

// HasTradeNo returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasTradeNo() bool {
	if o != nil && !isNil(o.TradeNo) {
		return true
	}

	return false
}

// SetTradeNo gets a reference to the given string and assigns it to the TradeNo field.
func (o *ServicesMakeRenewOrderResp) SetTradeNo(v string) {
	o.TradeNo = &v
}

// GetTradeProvider returns the TradeProvider field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetTradeProvider() string {
	if o == nil || isNil(o.TradeProvider) {
		var ret string
		return ret
	}
	return *o.TradeProvider
}

// GetTradeProviderOk returns a tuple with the TradeProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetTradeProviderOk() (*string, bool) {
	if o == nil || isNil(o.TradeProvider) {
    return nil, false
	}
	return o.TradeProvider, true
}

// HasTradeProvider returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasTradeProvider() bool {
	if o != nil && !isNil(o.TradeProvider) {
		return true
	}

	return false
}

// SetTradeProvider gets a reference to the given string and assigns it to the TradeProvider field.
func (o *ServicesMakeRenewOrderResp) SetTradeProvider(v string) {
	o.TradeProvider = &v
}

// GetTradeType returns the TradeType field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetTradeType() string {
	if o == nil || isNil(o.TradeType) {
		var ret string
		return ret
	}
	return *o.TradeType
}

// GetTradeTypeOk returns a tuple with the TradeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetTradeTypeOk() (*string, bool) {
	if o == nil || isNil(o.TradeType) {
    return nil, false
	}
	return o.TradeType, true
}

// HasTradeType returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasTradeType() bool {
	if o != nil && !isNil(o.TradeType) {
		return true
	}

	return false
}

// SetTradeType gets a reference to the given string and assigns it to the TradeType field.
func (o *ServicesMakeRenewOrderResp) SetTradeType(v string) {
	o.TradeType = &v
}

// GetWapUrl returns the WapUrl field value if set, zero value otherwise.
func (o *ServicesMakeRenewOrderResp) GetWapUrl() string {
	if o == nil || isNil(o.WapUrl) {
		var ret string
		return ret
	}
	return *o.WapUrl
}

// GetWapUrlOk returns a tuple with the WapUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeRenewOrderResp) GetWapUrlOk() (*string, bool) {
	if o == nil || isNil(o.WapUrl) {
    return nil, false
	}
	return o.WapUrl, true
}

// HasWapUrl returns a boolean if a field has been set.
func (o *ServicesMakeRenewOrderResp) HasWapUrl() bool {
	if o != nil && !isNil(o.WapUrl) {
		return true
	}

	return false
}

// SetWapUrl gets a reference to the given string and assigns it to the WapUrl field.
func (o *ServicesMakeRenewOrderResp) SetWapUrl(v string) {
	o.WapUrl = &v
}

func (o ServicesMakeRenewOrderResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CodeUrl) {
		toSerialize["code_url"] = o.CodeUrl
	}
	if !isNil(o.H5Url) {
		toSerialize["h5_url"] = o.H5Url
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.TradeNo) {
		toSerialize["trade_no"] = o.TradeNo
	}
	if !isNil(o.TradeProvider) {
		toSerialize["trade_provider"] = o.TradeProvider
	}
	if !isNil(o.TradeType) {
		toSerialize["trade_type"] = o.TradeType
	}
	if !isNil(o.WapUrl) {
		toSerialize["wap_url"] = o.WapUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServicesMakeRenewOrderResp) UnmarshalJSON(bytes []byte) (err error) {
	varServicesMakeRenewOrderResp := _ServicesMakeRenewOrderResp{}

	if err = json.Unmarshal(bytes, &varServicesMakeRenewOrderResp); err == nil {
		*o = ServicesMakeRenewOrderResp(varServicesMakeRenewOrderResp)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "code_url")
		delete(additionalProperties, "h5_url")
		delete(additionalProperties, "id")
		delete(additionalProperties, "trade_no")
		delete(additionalProperties, "trade_provider")
		delete(additionalProperties, "trade_type")
		delete(additionalProperties, "wap_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesMakeRenewOrderResp struct {
	value *ServicesMakeRenewOrderResp
	isSet bool
}

func (v NullableServicesMakeRenewOrderResp) Get() *ServicesMakeRenewOrderResp {
	return v.value
}

func (v *NullableServicesMakeRenewOrderResp) Set(val *ServicesMakeRenewOrderResp) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesMakeRenewOrderResp) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesMakeRenewOrderResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesMakeRenewOrderResp(val *ServicesMakeRenewOrderResp) *NullableServicesMakeRenewOrderResp {
	return &NullableServicesMakeRenewOrderResp{value: val, isSet: true}
}

func (v NullableServicesMakeRenewOrderResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesMakeRenewOrderResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


